// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0GuHnFEJBPkCbWTYRqRgB4J0FTVoCz9o',
    appId: '1:738762635997:web:e9c2315a567cb1d070b934',
    messagingSenderId: '738762635997',
    projectId: 'learningapp-d8109',
    authDomain: 'learningapp-d8109.firebaseapp.com',
    storageBucket: 'learningapp-d8109.appspot.com',
    measurementId: 'G-YDCJ4NGF8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8UCSutgwJh0bgK7oWANeWlzZLLhVM9kU',
    appId: '1:738762635997:android:c5d5eb62364f8a0170b934',
    messagingSenderId: '738762635997',
    projectId: 'learningapp-d8109',
    storageBucket: 'learningapp-d8109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6flQjpPhMd6Y9oU1nzFhXvMd2102KEyQ',
    appId: '1:738762635997:ios:01b7d4f2c70506ec70b934',
    messagingSenderId: '738762635997',
    projectId: 'learningapp-d8109',
    storageBucket: 'learningapp-d8109.appspot.com',
    iosClientId: '738762635997-oa2fs38mi04q929vcvdjci72nfb3vjst.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6flQjpPhMd6Y9oU1nzFhXvMd2102KEyQ',
    appId: '1:738762635997:ios:01b7d4f2c70506ec70b934',
    messagingSenderId: '738762635997',
    projectId: 'learningapp-d8109',
    storageBucket: 'learningapp-d8109.appspot.com',
    iosClientId: '738762635997-oa2fs38mi04q929vcvdjci72nfb3vjst.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );
}
